services:
  postgres:
    image: postgres:15
    container_name: pulpapp-db-liquibase
    environment:
      POSTGRES_DB: pulpapp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5436:5432"

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase-runner
    depends_on:
      - postgres
    volumes:
      - .:/liquibase/changelog
    working_dir: /liquibase/changelog
    command: >
      --url=jdbc:postgresql://postgres:5432/pulpapp_db
      --username=postgres
      --password=1234
      --changeLogFile=changelog-master.yaml
      --driver=org.postgresql.Driver
      --classpath=postgresql-42.7.10.jar
      update